[package]
name = "alkahest-rust-gen"
version.workspace = true
edition.workspace = true

[dependencies]
alkahest-core.workspace = true
alkahest-parse.workspace = true

quote.workspace = true
proc-macro2.workspace = true

